const WebSocket=require("ws");
const express=require("express");
const originalExpress=express;
const API_KEY=process.env.TWELVE_DATA_API_KEY||process.env.TWELVEDATA_API_KEY||process.env.TWELVE_DATA_KEY||"";
const SYMBOLS="XAU/USD,EUR/USD,GBP/USD,USD/JPY";
const UPSTREAM=API_KEY?`wss://ws.twelvedata.com/v1/quotes/price?apikey=${encodeURIComponent(API_KEY)}`:"";
let upstream=null,reconnectTimer=null,heartbeatTimer=null,browserWss=null,attached=false,patched=false;
const latestBySymbol=new Map();
function broadcast(x){if(!browserWss)return;const m=JSON.stringify(x);for(const c of browserWss.clients)if(c.readyState===WebSocket.OPEN){try{c.send(m)}catch(_){}}}
function reconnect(){if(reconnectTimer||!API_KEY)return;reconnectTimer=setTimeout(()=>{reconnectTimer=null;connect()},3000)}
function heartbeat(){clearInterval(heartbeatTimer);heartbeatTimer=setInterval(()=>{if(upstream?.readyState===WebSocket.OPEN){try{upstream.send(JSON.stringify({action:"heartbeat"}))}catch(_){}}},10000)}
function parse(raw){let d;try{d=JSON.parse(raw)}catch(_){return null}if(d.event==="price"){const price=Number(d.price);if(!Number.isFinite(price)||price<=0)return null;const ts=Number(d.timestamp);return{type:"tick",symbol:d.symbol||"XAU/USD",price,time:Number.isFinite(ts)?ts*1000:Date.now(),receivedAt:Date.now()}}if(d.event==="subscribe-status"){const status=String(d.status||"").toLowerCase();const symbols=d.params?.symbols||d.symbols||"";return{type:"subscription",status,message:d.message||`${status||"subscription"} ${symbols}`.trim()}}if(d.status==="error"||d.event==="error"||d.code>=400)return{type:"status",status:"error",message:d.message||"Twelve Data WebSocket error"};return null}
function connect(){if(!API_KEY){broadcast({type:"status",status:"disabled",message:"Twelve Data WebSocket API key is not configured."});return}if(upstream&&(upstream.readyState===WebSocket.OPEN||upstream.readyState===WebSocket.CONNECTING))return;try{upstream=new WebSocket(UPSTREAM);upstream.on("open",()=>{heartbeat();upstream.send(JSON.stringify({action:"subscribe",params:{symbols:SYMBOLS}}));broadcast({type:"status",status:"connecting",message:"Subscribing to live prices…"})});upstream.on("message",raw=>{const d=parse(raw.toString());if(!d)return;if(d.type==="tick"){latestBySymbol.set(d.symbol,d);broadcast(d)}else if(d.type==="subscription"){const ok=d.status.includes("success")||d.status.includes("ok")||d.status.includes("partial");broadcast({type:"status",status:ok?"connected":"error",message:d.message||"Subscription status received"})}else broadcast(d)});upstream.on("error",e=>broadcast({type:"status",status:"error",message:`Live tick stream error: ${e.message||"connection error"}`}));upstream.on("close",()=>{clearInterval(heartbeatTimer);heartbeatTimer=null;upstream=null;broadcast({type:"status",status:"reconnecting",message:"LIVE TICK STREAM RECONNECTING"});reconnect()})}catch(e){upstream=null;broadcast({type:"status",status:"error",message:e.message||"Unable to start live tick stream"});reconnect()}}
function attach(server){if(attached)return;attached=true;browserWss=new WebSocket.Server({server,path:"/ws/live"});browserWss.on("connection",client=>{client.send(JSON.stringify({type:"status",status:upstream?.readyState===WebSocket.OPEN?"connected":"reconnecting",message:upstream?.readyState===WebSocket.OPEN?"LIVE TICK STREAM":"WAITING FOR LIVE TICK STREAM"}));for(const t of latestBySymbol.values())client.send(JSON.stringify(t))});connect()}
function patch(){if(patched)return;patched=true;function patchedExpress(...args){const app=originalExpress(...args);const listen=app.listen.bind(app);app.listen=function(...a){const server=listen(...a);attach(server);return server};return app}Object.assign(patchedExpress,originalExpress);patchedExpress.static=originalExpress.static;const p=require.resolve("express");if(require.cache[p])require.cache[p].exports=patchedExpress}
patch();
