require("dotenv").config();
const express=require("express");
const cors=require("cors");
const bcrypt=require("bcryptjs");
const jwt=require("jsonwebtoken");
const Database=require("better-sqlite3");
const path=require("path");
const crypto=require("crypto");
const nodemailer=require("nodemailer");
const rateLimit=require("express-rate-limit");
const Stripe=require("stripe");
const {analyze,multiTimeframe,positionSize,TIMEFRAMES}=require("./analysis-engine");

const app=express();
const PORT=process.env.PORT||3000;
const JWT_SECRET=process.env.JWT_SECRET||"CHANGE_ME_IN_PRODUCTION";
const API_KEY=process.env.TWELVE_DATA_API_KEY||process.env.TWELVEDATA_API_KEY||process.env.TWELVE_DATA_KEY||"";
const STRIPE_SECRET=process.env.STRIPE_SECRET_KEY||"";
const STRIPE_WEBHOOK=process.env.STRIPE_WEBHOOK_SECRET||"";
const PREMIUM_PRICE=process.env.STRIPE_PREMIUM_PRICE_ID||"";
const APP_URL=(process.env.APP_URL||"").replace(/\/$/,"");
const stripe=STRIPE_SECRET?new Stripe(STRIPE_SECRET):null;
const db=new Database(path.join(__dirname,"priceedge.db"));
db.pragma("journal_mode=WAL");

db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS trades(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,pair TEXT NOT NULL,side TEXT NOT NULL,entry REAL,stop REAL,target REAL,result REAL DEFAULT 0,notes TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);`);
function addColumn(name,type,def){try{db.exec(`ALTER TABLE users ADD COLUMN ${name} ${type}${def?` DEFAULT ${def}`:""}`);}catch(e){if(!String(e.message).includes("duplicate column"))throw e;}}
addColumn("email_verified","INTEGER NOT NULL",process.env.NODE_ENV==="production"?"0":"1");
addColumn("verification_token","TEXT");addColumn("verification_expires","INTEGER");addColumn("stripe_customer_id","TEXT");addColumn("stripe_subscription_id","TEXT");addColumn("subscription_status","TEXT","'free'");addColumn("starting_balance","REAL","1000");addColumn("daily_loss_limit","REAL","20");

app.disable("x-powered-by");
app.use(cors({origin:true,credentials:false}));
app.use(express.raw({type:"application/vnd.priceedge.stripe-webhook",limit:"2mb"}));
app.post("/api/stripe/webhook",(req,res)=>{if(!stripe||!STRIPE_WEBHOOK)return res.status(503).send("Stripe is not configured");try{const event=stripe.webhooks.constructEvent(req.body,req.headers["stripe-signature"],STRIPE_WEBHOOK);const o=event.data.object;const email=o.customer_details?.email||o.customer_email||o.metadata?.email;if(event.type==="checkout.session.completed"){const u=db.prepare("SELECT id FROM users WHERE email=?").get(email?.toLowerCase());if(u)db.prepare("UPDATE users SET stripe_customer_id=?,stripe_subscription_id=?,subscription_status='active' WHERE id=?").run(o.customer,o.subscription,u.id);}else if(["customer.subscription.updated","customer.subscription.created","customer.subscription.deleted"].includes(event.type)){const u=db.prepare("SELECT id FROM users WHERE stripe_customer_id=? OR stripe_subscription_id=?").get(o.customer,o.id);if(u)db.prepare("UPDATE users SET stripe_subscription_id=?,subscription_status=? WHERE id=?").run(o.id,o.status==="active"||o.status==="trialing"?"active":o.status,u.id);}else if(event.type==="invoice.paid"){if(o.customer)db.prepare("UPDATE users SET subscription_status='active' WHERE stripe_customer_id=?").run(o.customer);}else if(event.type==="invoice.payment_failed"){if(o.customer)db.prepare("UPDATE users SET subscription_status='past_due' WHERE stripe_customer_id=?").run(o.customer);}res.json({received:true});}catch(e){console.error("STRIPE WEBHOOK",e.message);res.status(400).send("Webhook error");}});
app.use(express.json({limit:"200kb"}));
app.use(express.urlencoded({extended:true,limit:"50kb"}));
app.use(rateLimit({windowMs:60*1000,limit:120,standardHeaders:true,legacyHeaders:false}));
const authLimiter=rateLimit({windowMs:15*60*1000,limit:20,standardHeaders:true,legacyHeaders:false});
app.use(express.static(path.join(__dirname,"public"),{maxAge:process.env.NODE_ENV==="production"?"1h":0}));

function tokenFor(u){return jwt.sign({id:u.id,email:u.email},JWT_SECRET,{expiresIn:"7d"});}
function authRequired(req,res,next){const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"Authentication required."});try{req.user=jwt.verify(h.slice(7),JWT_SECRET);next();}catch(e){res.status(401).json({error:"Invalid or expired token."});}}
function premiumRequired(req,res,next){const u=db.prepare("SELECT subscription_status FROM users WHERE id=?").get(req.user.id);if(!u||u.subscription_status!=="active")return res.status(402).json({error:"Premium subscription required.",upgrade:true});next();}
function cleanEmail(v){return String(v||"").trim().toLowerCase();}
function safeUser(id){return db.prepare("SELECT id,email,created_at,email_verified,subscription_status,starting_balance,daily_loss_limit,stripe_customer_id,stripe_subscription_id FROM users WHERE id=?").get(id);}

const mailer=process.env.SMTP_HOST?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}):null;
async function sendVerification(email,token){if(!mailer)return false;const url=`${APP_URL||"http://localhost:"+PORT}/api/verify-email?token=${encodeURIComponent(token)}`;await mailer.sendMail({from:process.env.MAIL_FROM||process.env.SMTP_USER,to:email,subject:"Verify your PriceEdge account",text:`Verify your PriceEdge account: ${url}`,html:`<p>Verify your PriceEdge account.</p><p><a href="${url}">Verify email</a></p><p>This link expires in 24 hours.</p>`});return true;}

app.get("/api/health",(req,res)=>res.json({status:"ok",service:"PriceEdge",marketData:API_KEY?"configured":"missing",stripe:stripe&&PREMIUM_PRICE?"configured":"not configured",time:new Date().toISOString()}));
app.post("/api/register",authLimiter,async(req,res)=>{try{const email=cleanEmail(req.body.email),password=String(req.body.password||"");if(!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:"Enter a valid email address."});if(password.length<8)return res.status(400).json({error:"Password must be at least 8 characters."});if(db.prepare("SELECT id FROM users WHERE email=?").get(email))return res.status(409).json({error:"An account with that email already exists."});const verified=process.env.NODE_ENV==="production"?0:1;const raw=crypto.randomBytes(32).toString("hex"),hash=await bcrypt.hash(password,12);const r=db.prepare("INSERT INTO users(email,password_hash,email_verified,verification_token,verification_expires) VALUES(?,?,?,?,?)").run(email,hash,verified,raw,Date.now()+86400000);if(!verified)await sendVerification(email,raw);const u=safeUser(r.lastInsertRowid);res.status(201).json({token:verified?tokenFor(u):null,user:u,verificationRequired:!verified});}catch(e){console.error("REGISTER",e);res.status(500).json({error:"Unable to create account."});}});
app.get("/api/verify-email",async(req,res)=>{const token=String(req.query.token||"");const u=db.prepare("SELECT id FROM users WHERE verification_token=? AND verification_expires>? ").get(token,Date.now());if(!u)return res.status(400).send("Verification link is invalid or expired. Return to PriceEdge and request a new verification email.");db.prepare("UPDATE users SET email_verified=1,verification_token=NULL,verification_expires=NULL WHERE id=?").run(u.id);res.redirect("/"+(APP_URL?"?verified=1":""));});
app.post("/api/resend-verification",authRequired,async(req,res)=>{const u=db.prepare("SELECT id,email,email_verified FROM users WHERE id=?").get(req.user.id);if(!u)return res.status(404).json({error:"Account not found."});if(u.email_verified)return res.json({ok:true,alreadyVerified:true});const token=crypto.randomBytes(32).toString("hex");db.prepare("UPDATE users SET verification_token=?,verification_expires=? WHERE id=?").run(token,Date.now()+86400000,u.id);const sent=await sendVerification(u.email,token);res.json({ok:true,sent});});
app.post("/api/login",authLimiter,async(req,res)=>{const email=cleanEmail(req.body.email),password=String(req.body.password||"");const u=db.prepare("SELECT * FROM users WHERE email=?").get(email);if(!u||!(await bcrypt.compare(password,u.password_hash)))return res.status(401).json({error:"Invalid email or password."});if(!u.email_verified)return res.status(403).json({error:"Please verify your email before logging in."});res.json({token:tokenFor(u),user:safeUser(u.id)});});
app.get("/api/me",authRequired,(req,res)=>{const u=safeUser(req.user.id);if(!u)return res.status(404).json({error:"User not found."});res.json({user:u,premium:u.subscription_status==="active"});});
app.patch("/api/settings",authRequired,(req,res)=>{const balance=Number(req.body.startingBalance),loss=Number(req.body.dailyLossLimit);if(!Number.isFinite(balance)||balance<=0||!Number.isFinite(loss)||loss<=0)return res.status(400).json({error:"Balance and daily loss limit must be positive."});db.prepare("UPDATE users SET starting_balance=?,daily_loss_limit=? WHERE id=?").run(balance,loss,req.user.id);res.json({user:safeUser(req.user.id)});});

const cache=new Map(),active=new Map();
const SYMBOLS=["XAU/USD","EUR/USD","GBP/USD","USD/JPY"];
const ALLOWED=["1min","5min","15min","1h","4h","1day"];
async function td(symbol,interval,size=300){if(!API_KEY)throw Error("Twelve Data API key is not configured.");const url=new URL("https://api.twelvedata.com/time_series");url.searchParams.set("symbol",symbol);url.searchParams.set("interval",interval);url.searchParams.set("outputsize",String(size));url.searchParams.set("order","asc");const r=await fetch(url,{headers:{Authorization:`apikey ${API_KEY}`},cache:"no-store"});const d=await r.json();if(!r.ok||d.status==="error"||!Array.isArray(d.values))throw Error(d.message||`Market-data request failed (${r.status}).`);return d.values.map(c=>({datetime:c.datetime,open:Number(c.open),high:Number(c.high),low:Number(c.low),close:Number(c.close)})).filter(c=>[c.open,c.high,c.low,c.close].every(Number.isFinite));}
async function market(symbol,interval,size=300){const key=`${symbol}|${interval}|${size}`,now=Date.now(),c=cache.get(key);if(c&&now-c.time<15000)return{values:c.values,cached:true,updatedAt:c.time};if(active.has(key))return active.get(key);const p=td(symbol,interval,size).then(values=>{cache.set(key,{values,time:Date.now()});return{values,cached:false,updatedAt:Date.now()};}).finally(()=>active.delete(key));active.set(key,p);return p;}
app.get("/api/candles",async(req,res)=>{const symbol=String(req.query.symbol||"XAU/USD");const interval=String(req.query.interval||"5min");if(!SYMBOLS.includes(symbol)||!ALLOWED.includes(interval))return res.status(400).json({error:"Unsupported symbol or timeframe."});try{const d=await market(symbol,interval,Math.min(Number(req.query.size)||300,500));res.json({status:"ok",values:d.values,source:"Twelve Data",cached:d.cached,updatedAt:new Date(d.updatedAt).toISOString()});}catch(e){res.status(503).json({error:e.message,retryable:true});}});
app.get("/api/multi-analysis",authRequired,premiumRequired,async(req,res)=>{const symbol=String(req.query.symbol||"XAU/USD");if(!SYMBOLS.includes(symbol))return res.status(400).json({error:"Unsupported symbol."});try{const entries=await Promise.all(TIMEFRAMES.map(async tf=>[tf,(await market(symbol,tf,300)).values]));const result=multiTimeframe(Object.fromEntries(entries));const risk=riskStatus(req.user.id);if(!risk.allowed&&result.decision){result.decision={...result.decision,action:"WAIT",entryReady:false,riskBlocked:true,reason:`Risk guard active: ${risk.reason}`};result.action="WAIT";result.reason=`Risk guard active: ${risk.reason}`;}res.json({symbol,...result,risk});}catch(e){res.status(503).json({error:e.message});}});
app.get("/api/analysis",async(req,res)=>{const symbol=String(req.query.symbol||"XAU/USD");if(!SYMBOLS.includes(symbol))return res.status(400).json({error:"Unsupported symbol."});try{const [m5,d1]=await Promise.all([market(symbol,"5min",300),market(symbol,"1day",100)]);const a=analyze(m5.values),daily=analyze(d1.values);res.json({symbol,m5:a,d1:daily,disclaimer:"Educational and analytical information only. Not financial advice."});}catch(e){res.status(503).json({error:e.message});}});
app.get("/api/macro",async(req,res)=>{try{const [dxy,us10y]=await Promise.all([market("DXY","1h",100),market("US10Y","1h",100)]);let realYield=null;if(process.env.FRED_API_KEY){const u=new URL("https://api.stlouisfed.org/fred/series/observations");u.searchParams.set("series_id","DFII10");u.searchParams.set("api_key",process.env.FRED_API_KEY);u.searchParams.set("file_type","json");u.searchParams.set("sort_order","desc");u.searchParams.set("limit","1");const r=await fetch(u);const j=await r.json();realYield=j.observations?.[0]||null;}res.json({dxy:dxy.values.at(-1)||null,us10y:us10y.values.at(-1)||null,realYield,source:"Twelve Data / FRED",note:"Macro inputs are context, not a standalone trading signal."});}catch(e){res.status(503).json({error:e.message});}});
app.get("/api/calendar",async(req,res)=>{const url=process.env.ECONOMIC_CALENDAR_URL;if(!url)return res.json({events:[],configured:false,note:"Connect a licensed economic-calendar provider to enable automatic news blackout windows."});try{const headers={Accept:"application/json"};if(process.env.ECONOMIC_CALENDAR_API_KEY)headers.Authorization=`Bearer ${process.env.ECONOMIC_CALENDAR_API_KEY}`;const r=await fetch(url,{headers});const d=await r.json();res.json({events:Array.isArray(d)?d:(d.events||[]),configured:true});}catch(e){res.status(503).json({error:"Economic calendar unavailable."});}});

function dailyLoss(userId){const today=new Date().toISOString().slice(0,10);const row=db.prepare("SELECT COALESCE(SUM(result),0) AS pnl FROM trades WHERE user_id=? AND substr(created_at,1,10)=?").get(userId,today);return Number(row.pnl||0);}
function riskStatus(userId){const u=safeUser(userId);if(!u)return{allowed:false,status:"ACCOUNT_ERROR",dailyPnl:0,dailyLossLimit:0,remainingLoss:0,reason:"Account not found."};const dailyPnl=dailyLoss(userId),limit=Math.max(0,Number(u.daily_loss_limit)||0),used=Math.max(0,-dailyPnl),remaining=Math.max(0,limit-used);if(remaining<=0)return{allowed:false,status:"DAILY_LIMIT",dailyPnl,dailyLossLimit:limit,remainingLoss:0,reason:"Daily loss limit reached."};return{allowed:true,status:remaining<limit?"REDUCED_CAPACITY":"OK",dailyPnl,dailyLossLimit:limit,remainingLoss:remaining,reason:remaining<limit?"Daily loss budget is partially used.":"Risk budget available."};}
app.get("/api/risk-status",authRequired,(req,res)=>res.json(riskStatus(req.user.id)));
app.get("/api/trades",authRequired,(req,res)=>{const rows=db.prepare("SELECT id,pair,side,entry,stop,target,result,notes,created_at FROM trades WHERE user_id=? ORDER BY id DESC LIMIT 500").all(req.user.id);res.json(rows);});
app.post("/api/trades",authRequired,(req,res)=>{const side=String(req.body.side||"").toUpperCase(),pair=String(req.body.pair||"XAU/USD"),entry=Number(req.body.entry),stop=Number(req.body.stop),target=Number(req.body.target),result=Number(req.body.result||0),notes=String(req.body.notes||"");if(!["BUY","SELL"].includes(side)||!Number.isFinite(entry)||!Number.isFinite(stop)||!Number.isFinite(target))return res.status(400).json({error:"Valid side, entry, stop and target are required."});if((side==="BUY"&&!(stop<entry&&target>entry))||(side==="SELL"&&!(stop>entry&&target<entry)))return res.status(400).json({error:"Stop and target must be on the correct side of entry."});const u=safeUser(req.user.id);const risk=Math.abs(entry-stop),reward=Math.abs(target-entry);if(reward/risk<2)return res.status(400).json({error:"PriceEdge requires a minimum 1:2 risk-to-reward ratio."});const guard=riskStatus(req.user.id);if(!guard.allowed)return res.status(403).json({error:guard.reason,code:guard.status,risk:guard});const nextLoss=dailyLoss(req.user.id)+Math.min(0,result);if(nextLoss<-(u.daily_loss_limit||20))return res.status(403).json({error:"Daily loss limit reached. Trading journal is paused for today."});const r=db.prepare("INSERT INTO trades(user_id,pair,side,entry,stop,target,result,notes) VALUES(?,?,?,?,?,?,?,?)").run(req.user.id,pair,side,entry,stop,target,Number.isFinite(result)?result:0,notes);res.status(201).json(db.prepare("SELECT * FROM trades WHERE id=?").get(r.lastInsertRowid));});
app.get("/api/risk",authRequired,(req,res)=>{const balance=Number(req.query.balance),riskPercent=Number(req.query.riskPercent),entry=Number(req.query.entry),stop=Number(req.query.stop),contractSize=Number(req.query.contractSize||100);if(riskPercent>2)return res.status(400).json({error:"Maximum supported risk is 2% per trade."});const guard=riskStatus(req.user.id);if(!guard.allowed)return res.status(403).json({error:guard.reason,code:guard.status,risk:guard});const out=positionSize({balance,riskPercent,entry,stop,contractSize});if(!out)return res.status(400).json({error:"Invalid risk inputs."});const remainingRiskAmount=Math.min(out.riskAmount,guard.remainingLoss);if(out.riskAmount>guard.remainingLoss)return res.status(400).json({error:`Requested risk exceeds today's remaining loss budget of ${guard.remainingLoss.toFixed(2)}.`,code:"DAILY_BUDGET_EXCEEDED",risk:guard,requestedRisk:out.riskAmount});res.json({...out,dailyPnl:guard.dailyPnl,dailyLossLimit:guard.dailyLossLimit,remainingLoss:guard.remainingLoss,riskStatus:guard.status,remainingRiskAmount});});

app.post("/api/billing/checkout",authRequired,async(req,res)=>{if(!stripe||!PREMIUM_PRICE)return res.status(503).json({error:"Stripe is not configured yet."});const u=safeUser(req.user.id);try{let customer;if(u.stripe_customer_id)customer=await stripe.customers.retrieve(u.stripe_customer_id);else customer=await stripe.customers.create({email:u.email,metadata:{priceedge_user_id:String(u.id)}});db.prepare("UPDATE users SET stripe_customer_id=? WHERE id=?").run(customer.id,u.id);const session=await stripe.checkout.sessions.create({mode:"subscription",customer:customer.id,line_items:[{price:PREMIUM_PRICE,quantity:1}],success_url:`${APP_URL||"http://localhost:"+PORT}/?billing=success`,cancel_url:`${APP_URL||"http://localhost:"+PORT}/?billing=cancelled`,metadata:{priceedge_user_id:String(u.id)}});res.json({url:session.url});}catch(e){console.error("CHECKOUT",e);res.status(500).json({error:"Unable to start checkout."});}});
app.post("/api/billing/portal",authRequired,async(req,res)=>{if(!stripe)return res.status(503).json({error:"Stripe is not configured yet."});const u=safeUser(req.user.id);if(!u.stripe_customer_id)return res.status(400).json({error:"No Stripe customer exists for this account."});try{const s=await stripe.billingPortal.sessions.create({customer:u.stripe_customer_id,return_url:APP_URL||`http://localhost:${PORT}`});res.json({url:s.url});}catch(e){res.status(500).json({error:"Unable to open billing portal."});}});
app.get("/api/billing/status",authRequired,(req,res)=>{const u=safeUser(req.user.id);res.json({status:u.subscription_status,premium:u.subscription_status==="active"});});

app.get("*",(req,res)=>{if(req.path.startsWith("/api/"))return res.status(404).json({error:"API endpoint not found."});res.sendFile(path.join(__dirname,"public","index.html"));});
app.use((err,req,res,next)=>{console.error("SERVER ERROR",err);if(res.headersSent)return next(err);res.status(500).json({error:"Internal PriceEdge server error."});});
app.listen(PORT,()=>console.log(`PriceEdge running on ${PORT}; Twelve Data ${API_KEY?"configured":"missing"}; Stripe ${stripe&&PREMIUM_PRICE?"configured":"not configured"}`));